import { useEffect, useState, type FormEvent } from 'react';
import { api, messageForError } from '../../lib/api';
import { useAuth } from '../../context/AuthContext';
import { useModal } from '../../context/ModalContext';

export default function BookingPage({ hotelId }: { hotelId?: string }) {
  const { user } = useAuth(); const { navigate } = useModal(); const [hotel, setHotel] = useState<any>(null); const [rooms, setRooms] = useState<any[]>([]); const [roomId, setRoomId] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(true);
  const today = new Date().toISOString().slice(0, 10); const [form, setForm] = useState({ date_arrivee: today, date_depart: '', nombre_personnes: '1' });
  useEffect(() => { if (!hotelId) return; api(`/hotel/${hotelId}`).then(data => { setHotel(data); const available = (data.chambres || []).filter((room: any) => room.statut === 'disponible'); setRooms(available); if (available[0]) setRoomId(String(available[0].id)); }).catch(e => setError(messageForError(e))).finally(() => setLoading(false)); }, [hotelId]);
  const selected = rooms.find(room => String(room.id) === roomId);
  const reserve = async (e: FormEvent) => { e.preventDefault(); if (!user || user.role !== 'client') { navigate('/connexion'); return; } try { const reservation = await api('/client/reservations', { method: 'POST', body: JSON.stringify({ chambre_id: Number(roomId), date_arrivee: form.date_arrivee, date_depart: form.date_depart, nombre_personnes: Number(form.nombre_personnes), acompte: selected ? Number(selected.prix_nuit) * 0.2 : 0 }) }); setSuccess(`Réservation ${reservation.numero_reservation} enregistrée avec succès.`); } catch (caught) { setError(messageForError(caught)); } };
  if (loading) return <main className="min-h-screen p-32 text-center">Chargement…</main>; if (!hotel) return <main className="min-h-screen p-32 text-center">Hôtel introuvable.</main>;
  return <main className="min-h-screen bg-slate-100 px-4 pb-16 pt-28"><div className="mx-auto max-w-5xl"><button onClick={() => navigate('/')} className="text-sm font-bold text-green-700">← Retour au catalogue</button><section className="mt-4 overflow-hidden rounded-3xl bg-white shadow-sm"><img src={hotel.logo || '/hotel-yop1.jpg'} alt="" className="h-64 w-full object-cover" /><div className="p-7"><p className="text-sm font-bold text-orange-600">{hotel.quartier || hotel.ville}</p><h1 className="text-3xl font-black">{hotel.nom}</h1><p className="mt-3 text-slate-600">{hotel.description}</p></div></section><div className="mt-7 grid gap-7 lg:grid-cols-2"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Chambres disponibles</h2><div className="mt-4 space-y-3">{rooms.map(room => <label key={room.id} className="flex cursor-pointer items-center justify-between rounded-xl border p-4 has-[:checked]:border-green-600"><span><input type="radio" name="room" checked={roomId === String(room.id)} onChange={() => setRoomId(String(room.id))} className="mr-3" /><b>Chambre {room.numero_chambre}</b> · {room.type}<small className="block ml-7 text-slate-500">Capacité : {room.capacite} personne(s)</small></span><strong>{Number(room.prix_nuit).toLocaleString()} FCFA/nuit</strong></label>)}{!rooms.length && <p className="text-slate-500">Aucune chambre disponible pour le moment.</p>}</div></section><form onSubmit={reserve} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Réserver</h2><p className="mt-2 text-sm text-slate-500">Vous devez être connecté avec un compte client.</p><div className="mt-5 space-y-4"><label className="block text-sm font-bold">Arrivée<input required min={today} type="date" value={form.date_arrivee} onChange={e => setForm({ ...form, date_arrivee: e.target.value })} className="mt-1 w-full rounded-xl border p-3" /></label><label className="block text-sm font-bold">Départ<input required min={form.date_arrivee} type="date" value={form.date_depart} onChange={e => setForm({ ...form, date_depart: e.target.value })} className="mt-1 w-full rounded-xl border p-3" /></label><label className="block text-sm font-bold">Nombre de personnes<input required min="1" type="number" value={form.nombre_personnes} onChange={e => setForm({ ...form, nombre_personnes: e.target.value })} className="mt-1 w-full rounded-xl border p-3" /></label>{(error || success) && <p className={`rounded-xl p-3 text-sm ${error ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700'}`}>{error || success}</p>}<button disabled={!roomId} className="w-full rounded-xl bg-green-600 py-3 font-bold text-white disabled:opacity-50">{user?.role === 'client' ? 'Confirmer la réservation' : 'Se connecter pour réserver'}</button></div></form></div></div></main>;
}
