import { useEffect, useMemo, useState } from 'react';
import { api, messageForError } from '../lib/api';
import { useModal } from '../context/ModalContext';

export default function SidebarreZonne() {
  const { navigate } = useModal(); const [hotels, setHotels] = useState([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { api('/hotel/').then(setHotels).catch(e => setError(messageForError(e))).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => hotels.filter(h => `${h.nom} ${h.ville || ''} ${h.quartier || ''}`.toLowerCase().includes(query.toLowerCase()) && h.statut !== 'suspendu' && h.statut !== 'rejete'), [hotels, query]);
  return <section id="chambres" className="min-h-[600px] bg-slate-50 px-5 py-16 scroll-mt-20"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-green-700">Catalogue en direct</p><h2 className="mt-1 text-3xl font-black text-slate-900">Hôtels et chambres disponibles</h2><p className="mt-2 text-sm text-slate-500">Les établissements affichés proviennent de l’API.</p></div><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Rechercher par hôtel, ville ou quartier" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 sm:max-w-sm" /></div>{error && <p className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}{loading ? <p className="mt-8 text-slate-500">Chargement des hôtels…</p> : <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{visible.map(hotel => <article key={hotel.id} className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><img src={hotel.logo || '/hotel-yop1.jpg'} alt="" className="h-44 w-full object-cover" /><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">{hotel.quartier || hotel.ville || 'Abidjan'}</p><h3 className="mt-1 text-xl font-black">{hotel.nom}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-500">{hotel.description || 'Découvrez les chambres et disponibilités de cet établissement.'}</p><button onClick={() => navigate(`/reservation/${hotel.id}`)} className="mt-5 w-full rounded-xl bg-green-600 py-3 text-sm font-bold text-white">Voir les chambres et réserver</button></div></article>)}{!visible.length && <p className="text-slate-500">Aucun hôtel ne correspond à votre recherche.</p>}</div>}</div></section>;
}
