import { useState } from 'react';

const initialOwners = [
  { name: 'M. Niang', hotel: 'Palais de Niangon', email: 'niang@grandh.ci', status: 'Actif', commune: 'Yopougon' },
  { name: 'Mme Koné', hotel: 'Hôtel Ivoire Palace', email: 'kone@grandh.ci', status: 'Actif', commune: 'Cocody' },
];
const initialHotels = [
  { name: 'Palais de Niangon', owner: 'M. Niang', commune: 'Yopougon', status: 'Vérifié' },
  { name: 'Hôtel Ivoire Palace', owner: 'Mme Koné', commune: 'Cocody', status: 'Vérifié' },
  { name: 'Résidence du Boss', owner: '—', commune: 'Yopougon', status: 'À valider' },
];
const menu = ['Vue générale', 'Propriétaires', 'Hôtels', 'Communes', 'Réservations', 'Contrôle qualité', 'Paramètres'];

const Badge = ({ children, tone = 'green' }) => <span className={`rounded-full px-3 py-1 text-xs font-bold ${tone === 'orange' ? 'bg-orange-100 text-orange-800' : tone === 'red' ? 'bg-red-100 text-red-700' : 'bg-emerald-100 text-emerald-800'}`}>{children}</span>;

export default function SuperAdminDashboard() {
  const [active, setActive] = useState('Vue générale');
  const [owners, setOwners] = useState(initialOwners);
  const [hotels, setHotels] = useState(initialHotels);
  const [communes, setCommunes] = useState(['Yopougon', 'Cocody', 'Marcory', 'Plateau', 'Koumassi']);
  const [ownerForm, setOwnerForm] = useState({ name: '', hotel: '', email: '', commune: 'Yopougon' });
  const [hotelForm, setHotelForm] = useState({ name: '', owner: '', commune: 'Yopougon' });
  const [commune, setCommune] = useState('');
  const [notice, setNotice] = useState('');
  const showNotice = (message) => { setNotice(message); window.setTimeout(() => setNotice(''), 3500); };
  const addOwner = (event) => { event.preventDefault(); setOwners((current) => [...current, { ...ownerForm, status: 'Invitation envoyée' }]); setOwnerForm({ name: '', hotel: '', email: '', commune: 'Yopougon' }); showNotice('Invitation propriétaire créée avec succès.'); };
  const addHotel = (event) => { event.preventDefault(); setHotels((current) => [...current, { ...hotelForm, status: 'À valider' }]); setHotelForm({ name: '', owner: '', commune: 'Yopougon' }); showNotice('Hôtel ajouté. Il est en attente de validation.'); };
  const addCommune = (event) => { event.preventDefault(); const value = commune.trim(); if (value && !communes.includes(value)) { setCommunes((current) => [...current, value]); showNotice(`${value} a été ajoutée aux zones.`); } setCommune(''); };
  const selectClass = 'mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-emerald-400';
  const inputClass = 'mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-emerald-400';

  const Overview = () => <><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['12', 'Propriétaires actifs'], ['18', 'Hôtels référencés'], ['126', 'Chambres publiées'], ['2,8 M', 'Volume réservé ce mois']].map(([number, label], index) => <article key={label} className="rounded-2xl bg-white p-5 shadow-sm"><p className={`text-2xl font-black ${index === 3 ? 'text-orange-600' : 'text-emerald-800'}`}>{number}</p><p className="mt-1 text-sm text-slate-500">{label}</p></article>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-5"><section className="rounded-3xl bg-white p-6 shadow-sm xl:col-span-3"><div className="flex items-center justify-between"><div><h2 className="font-black text-slate-950">Activité de la plateforme</h2><p className="text-xs text-slate-500">Réservations validées cette semaine</p></div><Badge>+18 %</Badge></div><div className="mt-8 flex h-36 items-end justify-between gap-2">{[42, 61, 55, 80, 70, 92, 76].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className={`w-full rounded-t-lg ${index === 5 ? 'bg-orange-500' : 'bg-emerald-600'}`} style={{ height: `${height}%` }} /><span className="text-[10px] text-slate-400">{['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'][index]}</span></div>)}</div></section><section className="rounded-3xl bg-slate-950 p-6 text-white xl:col-span-2"><p className="text-sm font-bold text-orange-300">À TRAITER</p><p className="mt-4 text-3xl font-black">3</p><p className="mt-1 text-sm text-slate-300">hôtels attendent une vérification.</p><button type="button" onClick={() => setActive('Contrôle qualité')} className="mt-6 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-950">Ouvrir le contrôle</button></section></div></>;
  const Owners = () => <div className="mt-7 grid gap-6 xl:grid-cols-5"><section className="rounded-3xl bg-white p-6 shadow-sm xl:col-span-3"><h2 className="text-xl font-black text-slate-950">Propriétaires administrés</h2><p className="mt-1 text-sm text-slate-500">Créez, suivez et désactivez les accès des gestionnaires.</p><div className="mt-5 divide-y divide-slate-100">{owners.map((owner, index) => <div key={`${owner.email}-${index}`} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-bold text-slate-950">{owner.name}</p><p className="text-sm text-slate-500">{owner.hotel} · {owner.commune}</p><p className="text-xs text-slate-400">{owner.email}</p></div><Badge tone={owner.status === 'Actif' ? 'green' : 'orange'}>{owner.status}</Badge></div>)}</div></section><form onSubmit={addOwner} className="rounded-3xl bg-emerald-800 p-6 text-white xl:col-span-2"><p className="text-xs font-black uppercase tracking-wider text-orange-200">Nouveau compte</p><h2 className="mt-1 text-xl font-black">Ajouter un propriétaire</h2><div className="mt-5 space-y-3">{[['name', 'Nom complet'], ['hotel', 'Nom de l’hôtel'], ['email', 'E-mail professionnel']].map(([field, label]) => <input key={field} required type={field === 'email' ? 'email' : 'text'} value={ownerForm[field]} onChange={(event) => setOwnerForm({ ...ownerForm, [field]: event.target.value })} placeholder={label} className="w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm text-white placeholder:text-emerald-100 outline-none" />)}<select value={ownerForm.commune} onChange={(event) => setOwnerForm({ ...ownerForm, commune: event.target.value })} className="w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm text-white outline-none">{communes.map((item) => <option key={item} className="text-slate-900">{item}</option>)}</select></div><button className="mt-5 w-full rounded-xl bg-orange-500 py-3 font-black text-white hover:bg-orange-600">Envoyer l’invitation</button></form></div>;
  const Hotels = () => <div className="mt-7 grid gap-6 xl:grid-cols-5"><section className="rounded-3xl bg-white p-6 shadow-sm xl:col-span-3"><h2 className="text-xl font-black text-slate-950">Hôtels de la plateforme</h2><div className="mt-5 divide-y divide-slate-100">{hotels.map((hotel, index) => <div key={`${hotel.name}-${index}`} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-bold text-slate-950">{hotel.name}</p><p className="text-sm text-slate-500">{hotel.commune} · Gestionnaire : {hotel.owner || 'Non assigné'}</p></div><Badge tone={hotel.status === 'Vérifié' ? 'green' : 'orange'}>{hotel.status}</Badge></div>)}</div></section><form onSubmit={addHotel} className="rounded-3xl bg-white p-6 shadow-sm xl:col-span-2"><p className="text-xs font-black uppercase tracking-wider text-orange-600">Référencement</p><h2 className="mt-1 text-xl font-black text-slate-950">Ajouter un hôtel</h2><div className="mt-5 space-y-3"><input required value={hotelForm.name} onChange={(event) => setHotelForm({ ...hotelForm, name: event.target.value })} placeholder="Nom de l’hôtel" className={inputClass.replace('mt-1 ', '')} /><input required value={hotelForm.owner} onChange={(event) => setHotelForm({ ...hotelForm, owner: event.target.value })} placeholder="Nom du propriétaire" className={inputClass.replace('mt-1 ', '')} /><select value={hotelForm.commune} onChange={(event) => setHotelForm({ ...hotelForm, commune: event.target.value })} className={selectClass.replace('mt-1 ', '')}>{communes.map((item) => <option key={item}>{item}</option>)}</select></div><button className="mt-5 w-full rounded-xl bg-emerald-700 py-3 font-black text-white">Ajouter et contrôler</button></form></div>;
  const Communes = () => <div className="mt-7 grid gap-6 lg:grid-cols-5"><section className="rounded-3xl bg-white p-6 shadow-sm lg:col-span-3"><h2 className="text-xl font-black text-slate-950">Communes et zones</h2><p className="mt-1 text-sm text-slate-500">Les zones que les clients peuvent utiliser pour rechercher un hôtel.</p><div className="mt-5 flex flex-wrap gap-3">{communes.map((item) => <span key={item} className="rounded-full bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-800">{item}</span>)}</div></section><form onSubmit={addCommune} className="rounded-3xl bg-orange-50 p-6 shadow-sm lg:col-span-2"><h2 className="text-xl font-black text-slate-950">Ajouter une commune</h2><input required value={commune} onChange={(event) => setCommune(event.target.value)} placeholder="Ex. Bingerville" className={inputClass} /><button className="mt-4 w-full rounded-xl bg-orange-500 py-3 font-black text-white">Ajouter la zone</button></form></div>;
  const Reservations = () => <section className="mt-7 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-slate-950">Réservations de la plateforme</h2><div className="mt-5 divide-y divide-slate-100">{[['GRH-2048', 'Aminata Traoré', 'Palais de Niangon', '2 nuits', 'Confirmée'], ['GRH-2049', 'Koffi Yao', 'Hôtel Ivoire Palace', '3 heures', 'En attente'], ['GRH-2050', 'Mariam Coulibaly', 'Résidence du Boss', '1 nuit', 'Confirmée']].map(([code, client, hotel, duration, status]) => <div key={code} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-bold text-slate-950">{code} · {client}</p><p className="text-sm text-slate-500">{hotel} · {duration}</p></div><Badge tone={status === 'Confirmée' ? 'green' : 'orange'}>{status}</Badge></div>)}</div></section>;
  const Quality = () => <section className="mt-7 rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-slate-950">Contrôle qualité</h2><p className="mt-1 text-sm text-slate-500">Validez les informations, photos et tarifs avant publication.</p></div><Badge tone="orange">3 dossiers à traiter</Badge></div><div className="mt-6 grid gap-4 md:grid-cols-3">{['Résidence du Boss', 'Hôtel Belle Vue', 'Appartement Angré 8e'].map((hotel) => <article key={hotel} className="rounded-2xl border border-orange-100 bg-orange-50 p-5"><p className="font-black text-slate-950">{hotel}</p><p className="mt-1 text-sm text-slate-600">Photos et tarifs à vérifier.</p><div className="mt-4 flex gap-2"><button type="button" onClick={() => showNotice(`${hotel} a été validé.`)} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Valider</button><button type="button" onClick={() => showNotice(`Une demande de correction a été créée pour ${hotel}.`)} className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-orange-700">Demander correction</button></div></article>)}</div></section>;
  const Settings = () => <section className="mt-7 grid gap-6 lg:grid-cols-2"><article className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-slate-950">Règles de la plateforme</h2><label className="mt-5 block text-sm font-bold text-slate-700">Commission GrandH (%)<input type="number" defaultValue="10" className={inputClass} /></label><label className="mt-4 block text-sm font-bold text-slate-700">Acompte client (%)<input type="number" defaultValue="20" className={inputClass} /></label><button type="button" onClick={() => showNotice('Paramètres globaux enregistrés.')} className="mt-5 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white">Enregistrer</button></article><article className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-sm font-bold text-orange-300">Mobile Money & notifications</p><h2 className="mt-2 text-xl font-black">Configuration opérationnelle</h2><p className="mt-3 text-sm text-slate-300">Les paramètres de paiement, SMS et WhatsApp seront connectés au backend dans la prochaine étape.</p><button type="button" onClick={() => showNotice('Configuration prête à être reliée au backend.')} className="mt-5 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950">Configurer</button></article></section>;
  const content = active === 'Propriétaires' ? <Owners /> : active === 'Hôtels' ? <Hotels /> : active === 'Communes' ? <Communes /> : active === 'Réservations' ? <Reservations /> : active === 'Contrôle qualité' ? <Quality /> : active === 'Paramètres' ? <Settings /> : <Overview />;

  return <main className="min-h-screen bg-[#f7f3ea] px-4 pb-16 pt-28 sm:pt-32"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[250px_1fr]"><aside className="rounded-3xl bg-slate-950 p-5 text-white shadow-xl"><div className="border-b border-white/10 pb-5"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Administration centrale</p><h1 className="mt-2 text-2xl font-black">GrandH Admin</h1><p className="mt-1 text-xs text-slate-400">Pilotez toute la plateforme.</p></div><nav className="mt-5 space-y-2">{menu.map((item) => <button key={item} type="button" onClick={() => setActive(item)} className={`w-full rounded-xl px-4 py-3 text-left text-sm font-bold transition ${active === item ? 'bg-orange-500 text-white shadow-lg shadow-orange-950/20' : 'text-slate-300 hover:bg-white/10'}`}>{item}</button>)}</nav><div className="mt-8 rounded-2xl bg-white/10 p-4 text-xs text-slate-300"><p className="font-bold text-white">GrandH Côte d’Ivoire</p><p className="mt-1">Supervision des hôtels, propriétaires et réservations.</p></div></aside><section className="min-w-0"><header className="rounded-3xl bg-gradient-to-br from-emerald-800 via-emerald-700 to-orange-500 p-7 text-white shadow-lg"><p className="text-xs font-black uppercase tracking-[.2em] text-orange-100">Administration · Côte d’Ivoire</p><h1 className="mt-2 text-3xl font-black">{active}</h1><p className="mt-1 text-sm text-emerald-50">Gérez le réseau GrandH depuis un seul espace.</p></header>{notice && <p className="mt-5 rounded-2xl bg-emerald-100 px-5 py-4 text-sm font-bold text-emerald-900">✓ {notice}</p>}{content}</section></div></main>;
}
