import { useState } from 'react';

const initialAdmins = [{ name: 'M. Niang', hotel: 'Palais de Niangon', email: 'niang@grandh.ci', status: 'Actif' }, { name: 'Mme Koné', hotel: 'Hôtel Ivoire Palace', email: 'kone@grandh.ci', status: 'Actif' }];

export default function SuperAdminDashboard() {
  const [admins, setAdmins] = useState(initialAdmins);
  const [form, setForm] = useState({ name: '', hotel: '', email: '' });
  const addAdmin = (event) => { event.preventDefault(); setAdmins((current) => [...current, { ...form, status: 'Invitation envoyée' }]); setForm({ name: '', hotel: '', email: '' }); };
  return <main className="bg-slate-100 px-4 pb-16 pt-28 sm:pt-32"><div className="mx-auto max-w-7xl"><header className="rounded-3xl bg-slate-950 p-7 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Administration centrale</p><div className="mt-2 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-black">Tableau de bord super-admin</h1><p className="mt-2 text-sm text-slate-300">Gestion fictive des propriétaires et établissements GrandH.</p></div><span className="rounded-full bg-violet-500/20 px-4 py-2 text-sm font-bold text-violet-200">Mode démonstration</span></div></header><div className="mt-6 grid gap-5 md:grid-cols-3">{[['12', 'Propriétaires'], ['18', 'Hôtels actifs'], ['126', 'Chambres référencées']].map(([number, label]) => <article key={label} className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-3xl font-black text-violet-700">{number}</p><p className="mt-1 text-sm text-slate-500">{label}</p></article>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-5"><section className="rounded-3xl bg-white p-6 shadow-sm lg:col-span-3"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Propriétaires administrés</h2><p className="text-sm text-slate-500">Comptes illustratifs de la plateforme</p></div><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-bold text-violet-700">{admins.length} comptes</span></div><div className="mt-6 divide-y divide-slate-100">{admins.map((admin, index) => <div key={`${admin.email}-${index}`} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-bold text-slate-900">{admin.name}</p><p className="text-sm text-slate-500">{admin.hotel} · {admin.email}</p></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700">{admin.status}</span></div>)}</div></section><section className="rounded-3xl bg-violet-700 p-6 text-white lg:col-span-2"><p className="text-sm font-bold uppercase tracking-wider text-violet-200">Nouveau propriétaire</p><h2 className="mt-2 text-xl font-black">Ajouter un accès admin</h2><form onSubmit={addAdmin} className="mt-5 space-y-3">{[['name', 'Nom complet'], ['hotel', 'Nom de l’hôtel'], ['email', 'E-mail professionnel']].map(([field, label]) => <input key={field} required type={field === 'email' ? 'email' : 'text'} value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })} placeholder={label} className="w-full rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm text-white placeholder:text-violet-200 outline-none focus:bg-white/20" />)}<button className="w-full rounded-xl bg-white py-3 font-bold text-violet-800 hover:bg-violet-50">Enregistrer</button></form></section></div></div></main>;
}
