import { useEffect, useState, type FormEvent } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useModal } from '../../context/ModalContext';
import { api, messageForError } from '../../lib/api';

export default function SuperAdminDashboard() {
  const { user } = useAuth(); const { navigate } = useModal(); const [users, setUsers] = useState<any[]>([]); const [error, setError] = useState(''); const [form, setForm] = useState({ prenom: '', nom: '', email: '', telephone: '', password: '', password_confirmation: '', role: 'admin' });
  const load = async () => { try { setUsers(await api('/super-admin/users')); } catch (caught) { setError(messageForError(caught)); } };
  useEffect(() => { if (user?.role === 'super_admin') load(); }, [user]);
  const create = async (e: FormEvent) => { e.preventDefault(); setError(''); try { await api('/super-admin/users', { method: 'POST', body: JSON.stringify(form) }); setForm({ prenom: '', nom: '', email: '', telephone: '', password: '', password_confirmation: '', role: 'admin' }); await load(); } catch (caught) { setError(messageForError(caught)); } };
  const deactivate = async (id: number) => { try { await api(`/super-admin/users/${id}`, { method: 'DELETE' }); await load(); } catch (caught) { setError(messageForError(caught)); } };
  if (user?.role !== 'super_admin') return <main className="min-h-screen p-32 text-center"><h1 className="text-2xl font-black">Accès réservé au super-administrateur</h1><button onClick={() => navigate('/connexion')} className="mt-4 text-violet-700 underline">Se connecter</button></main>;
  const input = (key: keyof typeof form, label: string, type = 'text') => <label className="block text-sm font-bold">{label}<input required type={type} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded-xl border p-3" /></label>;
  return <main className="min-h-screen bg-slate-100 px-4 pb-16 pt-28"><div className="mx-auto max-w-6xl"><p className="font-bold uppercase tracking-widest text-violet-700">Administration</p><h1 className="text-3xl font-black">Utilisateurs</h1>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-7 grid gap-7 lg:grid-cols-3"><form onSubmit={create} className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Créer un compte</h2><div className="mt-4 space-y-3">{input('prenom', 'Prénom')}{input('nom', 'Nom')}{input('email', 'E-mail', 'email')}{input('telephone', 'Téléphone')}<label className="block text-sm font-bold">Rôle<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })} className="mt-1 w-full rounded-xl border p-3"><option value="admin">Administrateur</option><option value="gerant">Gérant</option><option value="client">Client</option></select></label>{input('password', 'Mot de passe', 'password')}{input('password_confirmation', 'Confirmation', 'password')}<button className="w-full rounded-xl bg-violet-700 py-3 font-bold text-white">Créer</button></div></form><section className="rounded-2xl bg-white p-6 shadow-sm lg:col-span-2"><h2 className="text-xl font-black">Comptes enregistrés</h2><div className="mt-4 space-y-3">{users.map(account => <article key={account.id} className="flex items-center justify-between rounded-xl border p-4"><div><b>{account.prenom} {account.nom}</b><p className="text-sm text-slate-500">{account.email} · {account.role} · {account.statut}</p></div>{account.statut === 'actif' && <button onClick={() => deactivate(account.id)} className="text-sm font-bold text-red-600">Désactiver</button>}</article>)}{!users.length && <p className="text-slate-500">Aucun compte à afficher.</p>}</div></section></div></div></main>;
}
